services:
  # minio:
  #   image: minio/minio:RELEASE.2025-04-22T22-12-26Z
  #   container_name: minio-server
  #   restart: always
  #   ports:
  #     # S3 对象存储API端口（程序对接用）
  #     - "9000:9000"
  #     # Web图形控制台端口（浏览器访问UI）
  #     - "9001:9001"
  #   environment:
  #     # 登录控制台、S3接口的账号（至少3位）
  #     MINIO_ROOT_USER: admin
  #     # 登录密码（至少8位，数字+字母）
  #     MINIO_ROOT_PASSWORD: Admin@123456
  #   volumes:
  #     # 持久化数据到本地 ./minio-data 文件夹
  #     - ./volumes/minio-data:/data
  #   command: server /data --console-address ":9001"
  rustfs:
    image: rustfs/rustfs:latest
    container_name: rustfs-server
    restart: always
    ports:
      - "9000:9000" # S3 API 端口
      - "9001:9001" # Web控制台端口
    environment:
      TZ: Asia/Shanghai
      # S3/后台登录账号密钥
      RUSTFS_ACCESS_KEY: admin
      RUSTFS_SECRET_KEY: Admin@123456
      # 开启Web管理控制台
      RUSTFS_CONSOLE_ENABLE: "true"
    volumes:
      - ./volumes/rustfs-data:/data
      - ./volumes/rustfs-logs:/logs
    command: server /data
